### ISSUE TITLE
Variable turns implementation might not be equivalent to Speed Dreams

### ISSUE THREAD

**Issue by zwn** [robotika/pyroborace#21]
According to https://github.com/robotika/pyroborace/pull/20#issuecomment-263115255 our implementation might not be equivalent with Speed Dreams implementation. Or at least we do not have any tests to prove the equivalence.

**Comment by m3d** [comment]
Currently failing example is [brondehach.xml](https://github.com/robotika/Roborace-Dreams/blob/56a8771d1ab385c4c81677ee66a46686749b3135/data/tracks/circuit/brondehach/brondehach.xml).
