### ISSUE TITLE
Handle properly nearest segment

### ISSUE THREAD

**Issue by m3d** [robotika/pyroborace#22]
It is necessary to keep context of the last passed segment, or use nearest segment over whole track (current version may crash due to artificial width and wrong selection of "nearest" (i.e. currently rather "close enough") segment. Beware of **Karwada** track, which is 8-loop with a bridge.

**Comment by zwn** [comment]
Is this really fixed? AFAIK the nearest segment calculation ignores Z coordinate. So in case of a bridge the closest segment is not even well defined.
